import ToastProvider from '@/components/ToastProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/ui/sidebar'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body>
        <div className="flex">
          <Sidebar />
          <main className="flex-1">
            <ToastProvider>{children}</ToastProvider>
          </main>
        </div>
      </body>
    </html>
  )
}